/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mikelvin.projeto.individual;

import java.awt.Color;
import java.util.Collections;
import java.util.Vector;

/**
 *
 * @author lucas pc
 */
public class ProjetoIndividual extends javax.swing.JFrame {

    /**
     * Creates new form TesteProva
     */
    public ProjetoIndividual() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btAcao = new javax.swing.JButton();
        pbPorcentagem1 = new javax.swing.JProgressBar();
        lbFrase1 = new javax.swing.JLabel();
        pbPorcentagem2 = new javax.swing.JProgressBar();
        lbFrase3 = new javax.swing.JLabel();
        pbPorcentagem3 = new javax.swing.JProgressBar();
        lbFrase2 = new javax.swing.JLabel();
        lbNome3 = new javax.swing.JLabel();
        lbNome4 = new javax.swing.JLabel();
        lbNome5 = new javax.swing.JLabel();
        lbMax1 = new javax.swing.JLabel();
        lbMax2 = new javax.swing.JLabel();
        lbMax3 = new javax.swing.JLabel();
        lbMin2 = new javax.swing.JLabel();
        lbMin1 = new javax.swing.JLabel();
        lbMin3 = new javax.swing.JLabel();
        lbMedia1 = new javax.swing.JLabel();
        lbMedia2 = new javax.swing.JLabel();
        lbMedia3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btAcao.setBackground(new java.awt.Color(255, 255, 255));
        btAcao.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        btAcao.setText("Análisar componentes");
        btAcao.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btAcao.setBorderPainted(false);
        btAcao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btAcao.setMargin(new java.awt.Insets(3, 14, 3, 14));
        btAcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAcaoActionPerformed(evt);
            }
        });

        pbPorcentagem1.setBackground(new java.awt.Color(0, 102, 255));
        pbPorcentagem1.setForeground(new java.awt.Color(0, 0, 0));
        pbPorcentagem1.setStringPainted(true);

        lbFrase1.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N

        pbPorcentagem2.setBackground(new java.awt.Color(0, 51, 255));
        pbPorcentagem2.setForeground(new java.awt.Color(0, 0, 0));
        pbPorcentagem2.setStringPainted(true);

        lbFrase3.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N

        pbPorcentagem3.setBackground(new java.awt.Color(51, 51, 51));
        pbPorcentagem3.setForeground(new java.awt.Color(0, 0, 0));
        pbPorcentagem3.setStringPainted(true);

        lbFrase2.setFont(new java.awt.Font("Gill Sans MT", 1, 12)); // NOI18N

        lbNome3.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbNome3.setText("Memória");

        lbNome4.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbNome4.setText("Disco");

        lbNome5.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        lbNome5.setText("Processador");

        lbMax1.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMax2.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMax3.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMin2.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMin1.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMin3.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMedia1.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMedia2.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        lbMedia3.setFont(new java.awt.Font("Gill Sans MT", 1, 11)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbNome5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMax1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMin1, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pbPorcentagem1, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbFrase1, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbNome3)
                                        .addGap(31, 31, 31)
                                        .addComponent(lbMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMedia2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pbPorcentagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(lbNome4)
                                        .addGap(54, 54, 54)
                                        .addComponent(lbMax3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMin3, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbMedia3, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(pbPorcentagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lbFrase3, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(lbFrase2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbMax1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbNome5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(lbMin1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lbMedia1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pbPorcentagem1, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                            .addComponent(lbFrase1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbNome3)
                                .addComponent(lbMax2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbMedia2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbMin2, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbFrase2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pbPorcentagem2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNome4)
                    .addComponent(lbMedia3, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbMax3, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbMin3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pbPorcentagem3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbFrase3, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAcao, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        //  Vetores de cada componente para guardar os dados
        Vector  vAnalise1 = new Vector();
        Vector  vAnalise2 = new Vector();
        Vector  vAnalise3 = new Vector();
        
        //  Váriavel do tipo inteira para receber os valores que futuramente serão gerados
        Integer tProcessador = 0;
        //  Contador para ir contando quantos valores foram incluidos no vetor
        Integer cProcessador = 0;
        
        //  Váriavel do tipo inteira para receber os valores que futuramente serão gerados
        Integer tMemoria = 0;
        //  Contador para ir contando quantos valores foram incluidos no vetor
        Integer cMemoria = 0;
        
        //  Váriavel do tipo inteira para receber os valores que futuramente serão gerados
        Integer tDisco = 0;
        //  Contador para ir contando quantos valores foram incluidos no vetor
        Integer cDisco = 0;
        
    private void btAcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAcaoActionPerformed
        //  Gerando valores aleatórios para cada componente
        Integer n1 = (int) (Math.random()*101);
        Integer n2 = (int) (Math.random()*101);
        Integer n3 = (int) (Math.random()*101);
 
        //  Atribuindo os valores aleatórios nos vetores
        vAnalise1.add(n1);
        vAnalise2.add(n2);
        vAnalise3.add(n3);
        
        //  O cálculo da média é no seguinte raciocínio:
        //  A váriavel t(Componente) vai somando os valores aleatórios que foram gerados
        //  A váriavel c(Componente) vai contando quantas vezes o botão foi clicado
        //  Sendo assim, o cálculo da média é simplesmente dividir o total atribuido pela quantidade de cliques (quantidade de números atribuidos)
        //  Ou seja:
        //  Soma dos valores aleatórios / quantidade de vezes que os valores foram atribuidos ao vetor = média
        
        //  Média Processador
        tProcessador += n1;
        cProcessador += 1;
        float mProcessador = tProcessador/cProcessador;
        lbMedia1.setText(String.format("Média: %.0f %%", mProcessador));
        
        //  Média Memória
        tMemoria += n2;
        cMemoria += 1;
        float mMemoria = tMemoria/cMemoria;
        lbMedia2.setText(String.format("Média: %.0f %%", mMemoria));
        
        //  Média Disco
        tDisco += n3;
        cDisco += 1;
        float mDisco = tDisco/cDisco;
        lbMedia3.setText(String.format("Média: %.0f %%", mDisco));
        
        //  Alterando o valor da barra(ProgressBar) para o valor aleatório
        pbPorcentagem1.setValue(n1);
        pbPorcentagem2.setValue(n2); 
        pbPorcentagem3.setValue(n3); 
        
        //  Valor máximo de cada vetor
        lbMax1.setText(String.format("Max: %d %%", Collections.max(vAnalise1)));
        lbMax2.setText(String.format("Max: %d %%", Collections.max(vAnalise2)));
        lbMax3.setText(String.format("Max: %d %%", Collections.max(vAnalise3)));
        
        //  Valor mínimo de cada vetor
        lbMin1.setText(String.format("Min: %d %%", Collections.min(vAnalise1)));
        lbMin2.setText(String.format("Min: %d %%", Collections.min(vAnalise2)));
        lbMin3.setText(String.format("Min: %d %%", Collections.min(vAnalise3)));

        //  If's para descrever o estado do componente de acordo com o tamanho do valor aleatório gerado
        // Cada estado possui uma cor para melhor análise
        if (n1 <= 60) {
            lbFrase1.setText(String.format("Normal", n1));
            lbFrase1.setForeground(Color.decode("#006400"));
        }else if (n1 >60 && n1<=80) {
            lbFrase1.setForeground(Color.decode("#cc8400"));
            lbFrase1.setText(String.format("Preocupante", n1));
        } else {
             lbFrase1.setForeground(Color.RED);
             lbFrase1.setText(String.format("Crítico", n1));
        }
        
        if (n2 <= 60) {
            lbFrase2.setText(String.format("Normal", n2));
            lbFrase2.setForeground(Color.decode("#006400"));
        }else if (n2 >60 && n2<=80) {
            lbFrase2.setText(String.format("Preocupante", n2));
            lbFrase2.setForeground(Color.decode("#cc8400"));
        } else {
            lbFrase2.setText(String.format("Crítico", n2));
             lbFrase2.setForeground(Color.RED);
        }
        
      if (n3 <= 60) {
           lbFrase3.setText(String.format("Normal", n3));
          lbFrase3.setForeground(Color.decode("#006400"));
        }else if (n3 >60 && n3<=80) {
        lbFrase3.setText(String.format("Preocupante", n3));
          lbFrase3.setForeground(Color.decode("#cc8400"));
       } else {
           lbFrase3.setText(String.format("Crítico", n3));
           lbFrase3.setForeground(Color.RED);
       }
    }//GEN-LAST:event_btAcaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProjetoIndividual.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProjetoIndividual().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAcao;
    private javax.swing.JLabel lbFrase1;
    private javax.swing.JLabel lbFrase2;
    private javax.swing.JLabel lbFrase3;
    private javax.swing.JLabel lbMax1;
    private javax.swing.JLabel lbMax2;
    private javax.swing.JLabel lbMax3;
    private javax.swing.JLabel lbMedia1;
    private javax.swing.JLabel lbMedia2;
    private javax.swing.JLabel lbMedia3;
    private javax.swing.JLabel lbMin1;
    private javax.swing.JLabel lbMin2;
    private javax.swing.JLabel lbMin3;
    private javax.swing.JLabel lbNome3;
    private javax.swing.JLabel lbNome4;
    private javax.swing.JLabel lbNome5;
    private javax.swing.JProgressBar pbPorcentagem1;
    private javax.swing.JProgressBar pbPorcentagem2;
    private javax.swing.JProgressBar pbPorcentagem3;
    // End of variables declaration//GEN-END:variables
}
